language: julia
julia:
  - 1.6
  - 1.7
  - 1.8
  - 1.9

script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("GenomicAnnotations")'

jobs:
  allowed_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.9
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
