language: julia
julia:
  - 1.1
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("GenomicAnnotations")'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
