language: julia
julia:
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly

script:
  - julia ci_prep.jl
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("GenomicAnnotations")'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia -e 'using Pkg.Registry; Registry.add(Registry.RegistrySpec(url = "https://github.com/BioJulia/BioJuliaRegistry.git"))'
        - julia -e 'using Pkg.Registry; Registry.add(Registry.RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"))'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
