name = "GenomicAnnotations"
uuid = "4f8a0a0a-376d-5ac0-ab14-e88793df67f0"
authors = ["Karl Dyrhage <karl.dyrhage@icm.uu.se>"]
version = "0.2.4"

[deps]
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
BioGenerics = "0.1"
BioSequences = "2"
DataFrames = "0.20, 0.21, 0.22, 1"
TranscodingStreams = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
